### ISSUE TITLE
Consider using gleam-community/colour

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [catppuccin/gleam#1]
Would you consider stripping out the colour types and depending on [gleam_community_colour](https://hexdocs.pm/gleam_community_colour/) instead? We built the library so that all colour-related things could have a shared dependency and interoperate, it would be great if catppuccin joined the party!

P.S. I love the little cat line drawing in the readme 💕

**Comment by MAHcodes** [comment]
Absolutely, I'm grateful for your attention in this project!

**Comment by hayleigh-dot-dev** [comment]
I had a poke around and it looks like you might have to lose the constants because the colour type in the gleam-community package is opaque... 🤔

**Comment by MAHcodes** [comment]
right @hayleigh-dot-dev, however, after testing it, I've noticed that the conversion is not quite accurate, even after trying both `from_hsl` and `from_rgb`, and I'm pretty sure I'm not doing anything wrong, what do you think?  I would appreciate any insights or assistance in resolving this issue.

I'm thinking to provide binding methods for gleam_community_colour?

**Comment by hayleigh-dot-work** [comment]
Hmm we do have tests that should make sure conversions are correct, if you think there’s a bug could you open an issue with a reproduction and I’ll take a look at it! 

Ultimately your library of course but I’d prefer we find a way to make catppuccin work with the colour lib directly so other folks are incentivised to use both!

**Comment by MAHcodes** [comment]
ah, I was dividing rgb values by 100 instead of 255, my bad, I have published the updated version...

**Comment by hayleigh-dot-dev** [comment]
Oh excellent, thank you so much!
